id = "nyx"
name = "Nyx"
description = "A dark theme for Zed editor inspired by One Dark Pro."
version = "0.1.0"
schema_version = 1
authors = ["Dean Srebnik"]
repository = "https://github.com/load1n9/zed-theme"